In [1]:
import pandas as pd

In [ ]:
df= pd.read_csv('')

In [20]:
df= pd.read_csv('bucket_gap_analysis_GLD_2025-08-22_to_2025-08-29/pattern_summary.csv')

In [21]:
df

,pattern,occurrences,total_change,avg_total_change,avg_internal_change,avg_gap_adjustment,avg_volume,std_dev,consistency
0,PPPPP,77,9.9379,0.1291,0.1300,-0.0009,42957,0.3124,0.7620
1,NPPPP,31,3.1037,0.1001,0.0875,0.0126,89464,0.3750,0.7272
2,PNPPP,33,2.1586,0.0654,0.0746,-0.0092,55261,0.0863,0.9206
3,PPNPP,35,1.8641,0.0533,0.0311,0.0222,45594,0.1840,0.8446
4,NPPPN,25,1.7700,0.0708,0.0648,0.0060,74025,0.0893,0.9180
5,NPPNP,21,1.7207,0.0819,0.0851,-0.0031,77877,0.1190,0.8936
6,PPPPN,44,1.5199,0.0345,0.0425,-0.0079,61890,0.2399,0.8065
7,PPPNP,38,0.9215,0.0242,0.0326,-0.0083,67981,0.1669,0.8570
8,PNNPP,20,0.7118,0.0356,0.0272,0.0084,113706,0.1039,0.9059
9,PPNNP,19,0.5900,0.0311,-0.0086,0.0396,69359,0.1392,0.8778
10,PPPNN,23,0.5146,0.0224,0.0114,0.0109,116185,0.1734,0.8522
11,NNPPP,16,0.5142,0.0321,0.0255,0.0067,94298,0.0880,0.9191
12,PNPNP,23,0.2098,0.0091,0.0075,0.0016,105822,0.1150,0.8969
13,NPNPP,21,0.1969,0.0094,0.0047,0.0046,68849,0.0882,0.9189
14,PNPPN,12,0.0991,0.0083,-0.0122,0.0205,88961,0.2796,0.7815
15,PPNPN,21,-0.0678,-0.0032,-0.0262,0.0230,50933,0.1105,0.9005
16,NNPNP,8,-0.3498,-0.0437,-0.0100,-0.0337,80844,0.0982,0.9106
17,PNNPN,23,-0.3939,-0.0171,-0.0289,0.0118,73339,0.0578,0.9454
18,NPPNN,10,-0.4638,-0.0464,-0.0326,-0.0138,57748,0.1111,0.9000
19,NPNNP,15,-0.5426,-0.0362,-0.0410,0.0048,44434,0.0475,0.9547
20,NNNNP,6,-0.5800,-0.0967,-0.1075,0.0108,83398,0.0641,0.9397
21,NNNPP,17,-0.6234,-0.0367,-0.0408,0.0042,83520,0.0582,0.9450
22,NPNNN,9,-0.6856,-0.0762,-0.0831,0.0069,67806,0.0803,0.9257
23,PNNNP,13,-0.6908,-0.0531,-0.0753,0.0221,67641,0.0894,0.9179
24,PNPNN,12,-0.7645,-0.0637,-0.0583,-0.0054,111135,0.0780,0.9276
25,NPNPN,21,-0.9127,-0.0435,-0.0477,0.0042,122920,0.0677,0.9366
26,PPNNN,10,-0.9300,-0.0930,-0.1079,0.0149,64952,0.1293,0.8855
27,NNNNN,6,-1.0150,-0.1692,-0.1667,-0.0025,52854,0.0164,0.9838
28,NNPNN,13,-1.4982,-0.1152,-0.1194,0.0041,75904,0.1460,0.8726
29,NNNPN,11,-1.5589,-0.1417,-0.1386,-0.0031,65158,0.1601,0.8620
30,NNPPN,20,-1.7301,-0.0865,-0.0886,0.0021,86237,0.0899,0.9175
31,PNNNN,16,-1.8057,-0.1129,-0.1159,0.0030,57128,0.0926,0.9153

In [22]:
profit = df.loc[:,'total_change']

In [23]:
profit.sum()

np.float64(11.22)

In [24]:
318.07 - 306.8

11.269999999999982

In [25]:
df=pd.read_csv('combined_pattern_analysis.csv')

In [26]:
df

   pattern  offset_0  offset_1  offset_2  offset_3  offset_4
0    NNNNN   -1.0150   -1.9650   -1.5194   -0.9500   -0.9863
1    NNNNP   -0.5800   -0.8385   -0.6638   -0.8062   -0.8359
2    NNNPN   -1.5589   -0.8372   -0.7998   -0.7473   -0.9349
3    NNNPP   -0.6234   -1.1700   -0.7030   -0.8480   -0.5308
4    NNPNN   -1.4982   -1.3625   -0.9366   -1.4356   -0.6738
5    NNPNP   -0.3498   -0.8270   -0.5563   -0.4849   -1.5815
6    NNPPN   -1.7301   -1.1789   -0.3350   -0.6985   -0.6201
7    NNPPP    0.5142    0.3680    0.1151    0.6587    1.3057
8    NPNNN   -0.6856   -0.7380   -0.9692   -2.0863   -1.7824
9    NPNNP   -0.5426   -0.6191   -0.7166   -0.6925   -0.3207
10   NPNPN   -0.9127   -1.0666   -0.7519   -1.0367   -0.8924
11   NPNPP    0.1969    0.9500   -0.8358    1.5097    0.3410
12   NPPNN   -0.4638   -0.9849   -1.2902   -0.3889   -1.1427
13   NPPNP    1.7207   -0.7076    0.7365    0.8893   -0.1656
14   NPPPN    1.7700   -0.0555   -0.5219   -0.4727   -0.1800
15   NPPPP    3.1037    1.5115    1.9258    1.5614    7.0912
16   PNNNN   -1.8057   -0.6733   -0.5450   -0.7204   -0.5850
17   PNNNP   -0.6908   -1.5900   -1.1918   -0.2010   -0.9939
18   PNNPN   -0.3939   -0.7191   -0.0218   -1.2759   -0.5886
19   PNNPP    0.7118    0.1322    0.6809    0.8217    0.4583
20   PNPNN   -0.7645   -0.4300   -1.0819   -0.6722   -0.6817
21   PNPNP    0.2098    0.9348    0.3743    0.1404    0.9074
22   PNPPN    0.0991    0.4456    1.1703    1.1150    1.1099
23   PNPPP    2.1586    1.6120    1.2004    5.2262    4.0248
24   PPNNN   -0.9300   -0.6532   -0.2617   -0.2358   -0.8941
25   PPNNP    0.5900    1.5189    0.0134    0.8378    0.6915
26   PPNPN   -0.0678    0.5740    0.7969    1.0300    0.2679
27   PPNPP    1.8641    2.0277    3.0777    3.7483    1.1524
28   PPPNN    0.5146    0.1354    1.3502    0.4091   -0.7506
29   PPPNP    0.9215    4.4639    5.3092    1.0085    1.5353
30   PPPPN    1.5199    5.9539    1.8595    0.3955    0.9579
31   PPPPP    9.9379    7.5885    6.7588    6.2013    7.1677